name: Client Deployment Workflow

on:
  push:
    branches:
      - development
      - main
    paths:
      - "client/**/*"
  pull_request:
    branches:
      - development
      - main
    paths:
      - "client/**/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Code
        uses: actions/checkout@v2
      - name: Setting up Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm run install-client
      - run: npm run build-client --if-present
      - name: Deploying to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: "client"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "git-history-client"
          heroku_email: "jhomiguelflorianmendez20@gmail.com"
