name: Server Deployment Workflow

on:
  push:
    branches:
      - development
      - main
    paths:
      - "server/**/*"
  pull_request:
    branches:
      - development
      - main
    paths:
      - "server/**/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Code
        uses: actions/checkout@v2
      - name: Setting up Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm run install-server
      - run: npm run build-server --if-present
      - run: npm run test-server
      - name: Deploying to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: "server"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "git-history-server"
          heroku_email: "jhomiguelflorianmendez20@gmail.com"
          procfile: "web: npm run start:prod"
          useforce: true
        env:
          GITHUB_REPO_OWNER: Jhomiguel
          GITHUB_REPO_NAME: git-history
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
